### ISSUE TITLE
Smart Home extended to multigraph plugin with additional values

### ISSUE THREAD

**Issue by wvogel** [ma4nn/fritzbox-munin-fast#11]
[fritzbox_smart_home.py.txt](https://github.com/christophmassmann/fritzbox-munin-fast/files/5892079/fritzbox_smart_home.py.txt)

An attempt to extend smart home monitoring from temperatures to switch states, power values, power consumption and temperatures as a multi graph plugin.

![powers-day](https://user-images.githubusercontent.com/1346901/106242150-86281900-6207-11eb-94bc-b1a486ddb7c2.png)

![states-day](https://user-images.githubusercontent.com/1346901/106242219-9d670680-6207-11eb-8310-dc8a1053f83a.png)

**Comment by wvogel** [comment]
There needs to be an update to the DERIVE energy counters: those need to be integer values and are currently floating point values which leads to "nan" in graphs.

**Comment by ma4nn** [comment]
@wvogel cool looks nice and is working already for me👍 Can you please create a [PR for this change](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) when it's ready?

**Comment by wvogel** [comment]
I went over the script again to reflect all your changes since my last attempt and to ensure that going all smart home devices only those are taken into account that provide valid results. I tried a pull request...
