### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by thojo0** [ma4nn/fritzbox-munin-fast#4]
Hi there.

I have some suggestions what you could maybe change:

- #!/usr/bin/env python -> #!/usr/bin/env python3
- add an useTls env variable witch you can define in the plugin-conf.d/ folder

**Comment by ma4nn** [comment]
Hi @thojo0,

thanks for your input on this plugin!

I have created a PR for your requested changes (see linked pull requests). 
Can you please check if this is what you meant?

Best regards,
Christoph

**Comment by thojo0** [comment]
Jup, this is what I meant.
Thanks
