### ISSUE TITLE
fritzbox_smart_home_temperature.py fails due to missing user name

### ISSUE THREAD

**Issue by wvogel** [ma4nn/fritzbox-munin-fast#9]
And here's the fix:

Line 37:
      connection = FritzConnection(address=config.server, password=config.password, use_tls=config.useTls)
needs to be replaced by
      connection = FritzConnection(address=config.server, user=config.user, password=config.password, use_tls=config.useTls)

**Comment by ma4nn** [comment]
Hi @wvogel,

thanks for your contribution!

Can you please check the [linked PR](https://github.com/christophmassmann/fritzbox-munin-fast/pull/10) if that contains all your requested changes?

Best regards,
Christoph
